/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rslvyaxfofwtetrguzeh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzbHZ5YXhmb2Z3dGV0cmd1emVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzNDU5OTksImV4cCI6MjA5OTkyMTk5OX0.sOkxwKH2IdVJo4Kx5l_oJ6Sm-oPfGYx-G_n8PLNH44Y"